apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-home.fullname" . }}-config
data:
  DB_HOST: {{ include "smart-home.fullname" . }}-postgresql
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ include "smart-home.fullname" . }}-kafka:9092
  APP_LOGGING_LOGSTASH_HOST: "logstash-service"
  APP_LOGGING_LOGSTASH_PORT: "5044"