input {
  tcp {
    port => 5044
    host => "0.0.0.0"
    codec => json
  }
}

filter {
  mutate {
    add_tag => [ "smart_home_logic" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "smart-home-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}